version: "3.8"

services:
  controller:
    container_name: iot_controller
    build: .
    command: python iot_controller.py
    ports:
      - 8006:8006
    volumes:
      - type: bind
        source: ./data
        target: /iot-controller/data
      - type: bind
        source: ./config
        target: /iot-controller/config
      - type: bind
        source: ./logs
        target: /iot-controller/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.103:8006/health"]
      interval: 3600s
      timeout: 30s
      retries: 3
